# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 050f26ec6f01d0f3e6c339fd13f0e4eafbe2b12578c9aeb52327d915828ac981c626cfeb512bc3f2573c55b808fb9f92afc300d9bef291c5748e376860b30bbb

test:
  secret_key_base: 758e4ea1ca8401ac0d589c78ce18d7a46dab49c74a7ca53ae26a265fd18847a6b0c7766351d2a67a13b152c82aca628e9a03e238dcc54dfc4fd9c0acb3cf24e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
